name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - 'releases/*'

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@4797143fa54b2306fe78646b48cfa10395506635 # v1.47.0

  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Check
        run: npm run ci

      - name: Test
        run: npm run test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          milliseconds: 1000

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
