name: Renovate
on:
  push:
    # Also run on main branch to make cache available
    branches:
      - main
    paths:
      - 'renovate.json'
      - '.github/workflows/renovate.yaml'
  pull_request:
    paths:
      - 'renovate.json'
      - '.github/workflows/renovate.yaml'

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cybozu/renovate-dry-run-action@63557d78fa42104865120021dd20c7758a1f8511 # v1
        with:
          config-file: renovate.json
